language: node_js
cache:
  directories:
    - ~/.npm
node_js: 
  - '12'
git: 
  depth: 3
script:
  - yarn build
deploy: 
  provider: pages
  edge: true
  skip-cleanup: true
  keep_history: true
  github-token: \$\GITHUB-TOKEN
  locale-dir: dist/
  target-brach: gh-pages
  commit_message: "Deploy Release"
  on: 
    branch: master